name: "My JS Action"
description: "Does something with JS"
inputs:
  name:
    description: "Who to greet"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
  arguments:
    - ${{ inputs.name }}

