name: My TepeScript Action"
description: "A simple GitHub Action written in TypeScript"

inputs:
  name:
    description: "Name to greet"
    requred: true
outputs:
  greeting:
    description: "The final greeting message"

runs:
  using: "node20"
  main: "dist/index.js"
